version: '3'

services:

  redis:
    image: redis:6.2
    ports:
      - $REDIS_PORT:6379

  db:
    image: postgres:14
    stop_signal: SIGINT
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS

  maildev:
    image: djfarrelly/maildev:1.1.0
    ports:
      - $SMTP_PORT:25
      - $MAILDEV_PORT:80
