version: '3'

services:

  redis:
    image: redis:5.0
    ports:
      - $REDIS_PORT:6379

  db:
    image: postgres:14
    stop_signal: SIGINT
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
